[changelog]
header = ""
body = """
{% if version %}\
## [{{ version | trim_start_matches(pat="v") }}](https://github.com/visjs/ngx-vis/compare/{{ previous.version }}...{{ version }}) ({{ timestamp | date(format="%Y-%m-%d") }})
{% else %}\
## [Unreleased]
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}

{% for commit in commits %}\
* {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ commit.message | upper_first }} \
([{{ commit.id | truncate(length=7, end="") }}](https://github.com/visjs/ngx-vis/commit/{{ commit.id }}))\
{% if commit.breaking %} **BREAKING CHANGE**{% endif %}

{% endfor %}
{% endfor %}\n
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
sort_commits = "oldest"

commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactoring" },
    { message = "^doc|^docs", group = "Documentation" },
    { message = "^test", group = "Testing" },
    { message = "^chore\\(deps\\)", group = "Dependency Updates" },
    { message = "^chore", skip = true },
    { message = "^ci", skip = true },
    { message = "^style", skip = true },
    { body = ".*security", group = "Security" },
]

protect_breaking_commits = false
filter_commits = true